### ISSUE TITLE
Last migration is being run first by `lein migrate` for new (version 0) database

### ISSUE THREAD

**Issue by kenny-evitt** [macourtney/drift#32]
Here's the output when I run `lein migrate`:

```
Jan 06, 2016 5:32:53 PM sun.reflect.NativeMethodAccessorImpl invoke0
INFO: Current database version: 0
Jan 06, 2016 5:32:54 PM sun.reflect.NativeMethodAccessorImpl invoke0
INFO: Updating to version: 20151013202740
Jan 06, 2016 5:32:54 PM sun.reflect.NativeMethodAccessorImpl invoke0
INFO: Running ledgeries.migrations.20151013202740-modify-table-transaction-entries-allow-null-description-values up...
Exception in thread "main" java.sql.BatchUpdateException: Batch entry 0 ALTER TABLE transaction_entries ALTER COLUMN description DROP NOT NULL was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2598)
	at org.postgresql.core.v3.QueryExecutorImpl$1.handleError(QueryExecutorImpl.java:459)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:407)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2737)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:319)
	at clojure.java.jdbc$db_do_commands$fn__5268.invoke(jdbc.clj:520)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:480)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:519)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:623)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:513)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:847)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:617)
	at ledgeries.db$do_commands$fn__5396.invoke(db.clj:55)
	at clojure.java.jdbc$with_connection_STAR_.invoke(jdbc.clj:770)
	at ledgeries.db$do_commands.doInvoke(db.clj:54)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at ledgeries.migrations.20151013202740_modify_table_transaction_entries_allow_null_description_values$up.invoke(20151013202740_modify_table_transaction_entries_allow_null_description_values.clj:7)
	at clojure.lang.Var.invoke(Var.java:411)
	at drift.runner$run_migrate_up.invoke(runner.clj:41)
	at clojure.core$map$fn__4207.invoke(core.clj:2487)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30)
	at clojure.core.protocols$fn__6026.invoke(protocols.clj:54)
	at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6177)
	at drift.runner$migrate_up_all.invoke(runner.clj:67)
	at drift.runner$migrate_up.invoke(runner.clj:86)
	at drift.runner$update_to_version.invoke(runner.clj:120)
	at drift.execute$migrate$fn__717.invoke(execute.clj:28)
	at drift.core$with_init_config$fn__579.invoke(core.clj:30)
	at clojure.lang.AFn.applyToHelper(AFn.java:159)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:617)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1788)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at drift.config$with_config_map.invoke(config.clj:16)
	at drift.core$with_init_config.invoke(core.clj:28)
	at drift.execute$migrate.invoke(execute.clj:26)
	at drift.execute$run$fn__721.invoke(execute.clj:35)
	at clojure.lang.AFn.applyToHelper(AFn.java:159)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:617)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1788)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at drift.config$with_config_fn_symbol.invoke(config.clj:12)
	at drift.execute$run.invoke(execute.clj:33)
	at user$eval23.invoke(form-init7623668639265027663.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Subprocess failed
```

Very strangely, *20151013202740-modify-table-transaction-entries-allow-null-description-values* is the last migration, of 27 total migrations.

I'm running Drift 1.5.2. Output of `lein -v`:

```
Leiningen 2.5.3 on Java 1.8.0_65 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by macourtney** [comment]
Try updating to version 1.5.3 of Drift. I think this issue was fixed in that update.

**Comment by kenny-evitt** [comment]
@macourtney Thanks; I probably should have tried that first anyways.

**Comment by kenny-evitt** [comment]
@macourtney 1.5.3 worked! Thanks again :smile:
